spring.application.name=capstone

#JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Database
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://capstone-database.crgcuw6yaf9x.ap-northeast-2.rds.amazonaws.com:5432/capstonedb?sslmode=require
spring.datasource.username=capstone
spring.datasource.password=2uQP8A2dLX9W5fQ
spring.datasource.driver-class-name=org.postgresql.Driver

server.address=0.0.0.0

#MQTT
mqtt:
  broker-url: tcp://43.201.17.179:1883
  port: 1883
  client-id: spring
  subscribe-topic: /data/station/#
  publish-topic: /control/station