spring.application.name=capstone

#JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Database
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://capstone-database.crgcuw6yaf9x.ap-northeast-2.rds.amazonaws.com:5432/capstonedb
spring.datasource.username=capstone
spring.datasource.password=2uQP8A2dLX9W5fQ
spring.datasource.driver-class-name=org.postgresql.Driver

server.address=0.0.0.0

#MQTT
mqtt.broker-url=tcp://3.38.103.218:1883
mqtt.port=1883
mqtt.client-id=spring
mqtt.subscribe-topic=smartgrid/telemetry
mqtt.publish-topic=/control/station
mqtt.ai-request-topic=smartgrid/ai/request
mqtt.schedule-request-topic=smartgrid/schedule/request

ai.server.url=http://100.109.146.64:8000

# 기상청 API 인증키
weather.asos.key=b182d6fc0e89c2c3fc016491f6c020da8b125642f2e2b4902efabfbbe1a7f967
weather.forecast.key=E44EjYf-T4-OBI2H_v-Pvw