name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle 권한 부여
        run: chmod +x gradlew

      - name: 빌드
        run: ./gradlew build -x test

      - name: jar 확인
        run: ls build/libs

      - name: EC2로 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/"

      - name: 서버 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "기존 서버 종료"
            pkill -f 'java -jar' || true

            echo "jar 파일 확인"
            ls /home/ubuntu

            JAR_NAME=$(ls /home/ubuntu/*.jar | head -n 1)
            echo "실행 파일: $JAR_NAME"

            echo "서버 실행 (로그 확인)"
            java -jar $JAR_NAME